version: '3.1'

services:

  db:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

  adminer:
    container_name: adminerpg
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8091:8080